### ISSUE TITLE
cannot implement interface `fmt.Stringer` (and probably most other interfaces)

### ISSUE THREAD

**Issue by cosmos72** [containous/yaegi#251]
The following program `sample.go` triggers a panic:

```go
package main
import "fmt"
type Int int
func (I Int) String() string {
  return "foo"
}
func main() {
  var i Int
  var st fmt.Stringer = i
  fmt.Println(st.String())
}
```

Expected result:
```go
foo
```

Got:
```
panic: reflect.Set: value of type int is not assignable to type fmt.Stringer
```

**Comment by cosmos72** [comment]
By personal experience (see https://github.com/cosmos72/gomacro), this feature is impossible to implement using the `reflect` package, because it does not support creating new named types and adding methods to them.
It can only be emulated, and even that is *difficult*

**Comment by mvertes** [comment]
Yes, totally true.

We have done some efforts to workaround `reflect` limitations, and should be able to run this. This close example [_test/heap.go](https://github.com/containous/yaegi/blob/master/_test/heap.go) passes ok.
