### ISSUE TITLE
Implement readline support

### ISSUE THREAD

**Issue by llimllib** [containous/yaegi#253]
Without readline support, the repl is marginally useful:

Got:
```console
$ yaegi
> import ""typo"^A^[[C^[[C^[[C^C
```

Is this something you'd consider for this project, or would a usable REPL be out of scope and best suited for a companion project?

**Comment by mvertes** [comment]
The repl is minimalistic at the moment, and we wanted to start with no external dependencies, so yes I tend to see a real powerful REPL as a separate project, but no definitive opinion on that.

Note that you can always use [rlwrap](https://github.com/hanslub42/rlwrap) (install with your favorite package manager), and alias the yaegi command in `alias yaegi='rlwrap yaegi'` in your `~/.bashrc`,  to have history and command line edition.
