### ISSUE TITLE
repl example fails at import "fmt"

### ISSUE THREAD

**Issue by vielmetti** [containous/yaegi#254]
Related to #145 I think.

The documentation gives this example of the repl:

```console
$ yaegi
> 1 + 2
3
> import "fmt"
> fmt.Println("Hello World")
Hello World
>
```

However, when I go to try this, I get the following:

```console
$ go/bin/yaegi
> 1 + 2
3
> import "fmt"
unable to find source related to: "fmt"
```

Environment: Ubuntu 18 on an NVidia Tegra, using the Ubuntu bionic version of Go (1.10).

**Comment by mvertes** [comment]
Thanks for your report. Could you give us the output of `go env` command please ?

**Comment by mvertes** [comment]
Sorry missed it before, but the stdlib support (for imports and so on) requires go1.11 or go1.12. We should explain it in the doc!

**Comment by vielmetti** [comment]
OK, installed with Go 1.12. I'll open up a separate issue for the somewhat unexpected behavior I am seeing.
