### ISSUE TITLE
use of untyped nil

### ISSUE THREAD

**Issue by QuantumGhost** [containous/yaegi#269]
I found yaegi reported `use of untyped nil` when I was trying to import `go.uber.org/zap`.
After some digging, I found a minimal reproduction as below

```go
package demo

type A struct {}

func (a *A) Foo() {}

var (
	_a = A{}
	_Foo = _a.Foo
)
```

Expected result:
```console
$ yaegi ./demo.go
// ouput 
// nothing
```

Got:
```console
$ yaegi ./demo.go
// ouput
demo.go:9:2: use of untyped nil
```

**Comment by cuonglm** [comment]
A variant of this program which trigger a panic:

```
package main

type A struct{}

func (a *A) Foo() {}

func main() {
	a := A{}
	println(a.Foo() == nil)
}
```

Should I raise another bug?

**Comment by QuantumGhost** [comment]
@cuonglm I guess it's the same problem.

**Comment by cuonglm** [comment]
@QuantumGhost I'm not sure, because your example gives an error, while mine trigger a panic.
