### ISSUE TITLE
invalid code causes hang

### ISSUE THREAD

**Issue by mingrammer** [containous/yaegi#274]
```console
$ yaegi
> import fmt

```

I mistyped the `import "fmt"` as `import fmt`, and then it hung up (didn't crash, just stopped). So I couldn't do anything further.

I think it should throw the appropriate error messages for the import syntax error.

**Comment by pborman** [comment]
This appears to be more generic than that.  The following hangs:

```
$ yaegi
> .
```

I really like the idea of Yaegi and I hope these initial quirks can be addressed.

**Comment by Ocaenyth** [comment]
Anything that isn't valid code seems to make the interpreter hang from my experience
+1 for the addition of error messages and better handling

**Comment by mpl** [comment]
Closing because this is now all fixed. Both examples given in this conversation now return the prompt to the user. And they trigger error messages.
