### ISSUE TITLE
Is there a communication group for yaegi fans？

### ISSUE THREAD

**Issue by charlieliiii** [containous/yaegi#275]

**Comment by geraldcroes** [comment]
Not yet :-) In the meantime, Github is a nice place to show your support!

**Comment by ldez** [comment]
If you are at the GopherCon (San Diego) you can come speak we us :smiley:

**Comment by arcticicestudio** [comment]
A great and simply configurable solution could be [Spectrum][], the open source project that was bought by GitHub that get currently integrated into the page as an official way to create a platform for project communities. One of your GitHub organization account (`owner` role required) can login with the GitHub account and then create a new _community_.

[spectrum]: https://spectrum.chat

**Comment by ldez** [comment]
We will manage something quickly, stay tuned!

**Comment by ldez** [comment]
Enjoy :tada: https://community.containo.us/c/yaegi
