### ISSUE TITLE
Panic with go tip

### ISSUE THREAD

**Issue by fsouza** [containous/yaegi#285]
Very cool project, thanks for creating it! I hit a snag while testing it today, it looks like it panics when built with Go tip (``runtime.Version()`` doesn't return a value that looks like a version of Go, so ``v[1]`` is out of bounds).

```
$ go version
go version devel +919594830f Tue Jul 23 23:42:43 2019 +0000 linux/amd64
$ yaegi
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/containous/yaegi/interp.goNumVersion(0xc0000a81c0)
        /home/fsouza/src/github.com/containous/yaegi/interp/build.go:91 +0xa5
github.com/containous/yaegi/interp.init()
        /home/fsouza/src/github.com/containous/yaegi/interp/build.go:60 +0x26
```

It works fine if I recompile with Go 1.12.

Would you take a PR that makes it compatible with Go tip? I suppose we can assume all ``go1.x`` build tags are applicable if the tip is being used? Like, if someone is using tip, it better be up to date :see_no_evil:.

**Comment by ldez** [comment]
Hello, thanks :smiley: 

For now, Yaegi works only with go1.11 and go1.12 due to [stdlib mapping](https://github.com/containous/yaegi/tree/master/stdlib).

But as soon as the first stable 1.13 will be available we will add the support.

FYI we are working to improve our `goexports` commands.

**Comment by fsouza** [comment]
@ldez thanks for the info! :D
