### ISSUE TITLE
Support vendor imports

### ISSUE THREAD

**Issue by Ocaenyth** [containous/yaegi#288]
I'm currently using Go at work and I need to use private repositories, which I usually have in a `vendor` folder created by the `go mod vendor` command.
When I tried to run one of our examples for a project, I was met with the following error :
```
$ yaegi main.go
unable to find source related to: "path/to/my/package.git"
```

**Comment by james-lawrence** [comment]
is this a known bug? i'm running into it as well but given the labels not sure if its a bug or user error?

**Comment by mpl** [comment]
Vendored imports should now be supported, I think we can close this issue.
