### ISSUE TITLE
Some imports require alias name to work normal

### ISSUE THREAD

**Issue by tim-st** [containous/yaegi#298]
The package name of `github.com/tim-st/go-unicat` is `unicat` so the following example should work:
```
> import "github.com/tim-st/go-unicat"
0xc000124120
> unicat.From('R')
1:28: undefined: unicat
>
```

When doing an alias import instead with normal package name it works:
```
> import unicat "github.com/tim-st/go-unicat"
0xc00010c160
> unicat.From('R')
0
```
Tested in REPL latest version with `go version go1.12.7 windows/amd64` and `go version go1.12.7 linux/amd64`.

**Comment by mpl** [comment]
This is now fixed:

```
% yaegi
> import "github.com/tim-st/go-unicat"
: 0xc0002061e0
> unicat.From('R')
: 0
> 
```
