### ISSUE TITLE
type definition not implemented: sliceExpr 

### ISSUE THREAD

**Issue by vsel** [containous/yaegi#316]
When I try to peroform:
`a := "sdofjsdfj"`
`z := a[0:2]`
Result: `1:33: type definition not implemented: sliceExpr`

**Comment by mvertes** [comment]
The bug is due to the lack of slice expression processing in global space. The same problem is exposed in `sample.go`:

```go
package main

var a = "sdofjsdfj"
var z = a[0:2]

func main() {
        println(z)
}

// Output:
// sd
```

Which returns:

```console
$ yaegi ./sample.go
./sample.go:4:9: type definition not implemented: sliceExpr
