### ISSUE TITLE
typing () gets you stuck in the reply

### ISSUE THREAD

**Issue by fiws** [containous/yaegi#317]
This is a pretty silly bug. But it's still kind of annoying.

Pressing ctrl+c will stop the whole repl session.
This also happens for other chars. For example typing `>` also gets you stuck.

Type this in the repl:
```go
()
```

Expected result:
```console
 What are you even doing?
```

Got:

Me hammering random stuff:
```console
()




Aaargn
()
stahp
quit
EOF
how do i quit vim?
```

**Comment by mvertes** [comment]
Parse error handling in the REPL is rather crude at this moment, resulting in hang, and definitely needs to be improved. A difficulty here is that we have to tolerate incomplete blocks, waiting for a closing '"' or ')' or '}', etc, in the next line, and not fail too early. As a result, we do not fail at all. Hopefully, it is still possible to make better decision based on the precise AST error returned by the AST parser.

**Comment by fiws** [comment]
How about: ctrl+c just clears the input and ctrl+c twice exits? The node.js repl also works like this.

**Comment by mvertes** [comment]
Yes, sounds good, thank you for the suggestion.

**Comment by kortschak** [comment]
When/if #387 is merged, adding signal handling for termination of script execution (and other parts of the interpreter, as described here) will be trivial.

**Comment by mpl** [comment]
This seems to be fixed:

```
% yaegi
> ()
_.go:1:29: expected operand, found ')'
> 
```

So I think we can close.
