### ISSUE TITLE
ast parser errors may be ignored

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#328]
The following program `sample.go` triggers an unexpected result:

```go
println("hello")
```

Expected result:
```console
$ go run ./sample.go
package main: 
_test/bad0.go:1:1: expected 'package', found println
```

Got:
```console
$ yaegi ./sample.go
"hello"
```

**Comment by theclapp** [comment]
Are you suggesting that any yaegi interaction be a correctly parsable full Go program, or only .go files?

**Comment by mvertes** [comment]
The same code in the REPL is valid, and is correct in an incremental, line by line interpretation.

But it should not be allowed in batch mode. In .go files, we should have a behaviour identical to `go run`.

**Comment by mvertes** [comment]
Of course, providing a fully correct .go file in REPL, starting by `package` statement should work as well.

**Comment by mpl** [comment]
This is now fixed:

```
% yaegi run ./sample.go 
./sample.go:1:1: expected 'package', found println
```
