### ISSUE TITLE
Use a symbol without package qualifier

### ISSUE THREAD

**Issue by gmosx** [containous/yaegi#332]
I would like to pre-define some symbols that can be used from my evaled code without a package 'qualifier'. I tried to use:

```
import . "mypkg"
```

but seems this is not implemented. Any other ideas?

Btw, thanks for this very useful project!

**Comment by mvertes** [comment]
Support of `import .` is implemented:

```console
$ yaegi
> import . "fmt"
0xc000152140
> Println("Hello")
Hello
6
>
```
