### ISSUE TITLE
cannot import "github.com/boltdb/bolt"

### ISSUE THREAD

**Issue by nosarthur** [containous/yaegi#345]
The following program `sample.go` triggers a panic:

```go
package main

import _ "github.com/boltdb/bolt"

func main() {
// add a sample
}
```

Expected result:
```console
$ go run ./sample.go
// ouput
```

Got:
```console
$ yaegi ./sample.go
// ouput
unable to find source related to: "syscall"
```

**Comment by bysans** [comment]
You cannot use syscall in yaegi. It's notified in features at Readme file.

**Comment by ldez** [comment]
`syscall` are disabled by default https://github.com/containous/yaegi#features

So `syscall` cannot be used by the CLI but `syscall` can be used when you are using Yaegi as a lib.

- https://github.com/containous/yaegi#as-a-dynamic-extension-framework
- https://github.com/containous/yaegi/tree/master/stdlib/syscall
