### ISSUE TITLE
The embedded interpreter example panics

### ISSUE THREAD

**Issue by gbernady** [containous/yaegi#371]
I'm having problems running the [embedded interpreter go playground](https://play.golang.org/p/zzvw4VlerLP) linked in README. When I run the code, it panics:

```console
panic: unable to find source related to: "fmt"

goroutine 1 [running]:
main.main()
	/tmp/sandbox065718883/prog.go:15 +0x120
```

The same happens when I build & run this code locally when using Go 1.13 and a `go.mod` file looking like this:
```
module foo

go 1.13

require github.com/containous/yaegi v0.0.4
```

**Comment by ldez** [comment]
hello,

v0.0.4 is only compatible with go1.11 and go1.12

The next version will support go1.13
