### ISSUE TITLE
add command line option to set custom build tags

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#372]
#### Proposal

Add `-tags tag,list` to yaegi command, with the same effect as `go build -tags tag,list`, i.e defining the tags as custom build constraints used in comments such as `// +build !amd64 noasm`

#### Background

Some third party packages are using custom build tags to trigger assembly optimisations, or to avoid `unsafe` package, etc. 

For example, the package `google.golang.org/grpc` uses `purego` tag to avoid  dependency on `unsafe` package. Related to #260 

In another example, `gonum.org/v1/gonum/internal/math32` contains some implementation of Sqrt avoiding assembly dependency using `noasm` constraint. Related to #301.

#### Workarounds

No workaround known

**Comment by mvertes** [comment]
Another possibility is to add a yaegi directive in a special comment to set tags (and maybe other parameters, later), to be used in script source, before import statements:

```go
//yaegi: tags=noasm,appengine
import "google.golang.org/grpc"
```

**Comment by mvertes** [comment]
Change tags syntax in comment line to:

```go
// yaegi-tags: noasm appengine
```

**Comment by ldez** [comment]
Change tags syntax in comment line to:

```go
// yaegi:tags noasm appengine
```
