### ISSUE TITLE
interp: add cancellation context to Eval call

### ISSUE THREAD

**Issue by kortschak** [containous/yaegi#386]
#### Proposal

Provide a `context.Context` to the interpreter that can be used for timeout or cancellation.

#### Background

In the case where a code chunk is being executed within an interpreter within a larger application it may be the case that the interpreted code takes too long or will not terminate. In these situations it would be valuable to be able to halt the execution of the interpreter.

Note that it is still possible with a cancelled context for an interpreted chunk to hang if the hang is happening in non-interpreted code called by the interpreted chunk. I am not proposing a solution to this.

#### Workarounds

There is no work around except for running the `yaegi` command as a separate process and using interprocess communication.

**Comment by mvertes** [comment]
Fixed by #401
