### ISSUE TITLE
Assign function to variable

### ISSUE THREAD

**Issue by tehsphinx** [containous/yaegi#425]
The following program `sample.go` returns a wrong value:

```go
package main

func main() {
	var x = func(i int) int {
		return i + 2
	}
	z := x(2) + 3

	fmt.Println(z)
}

```

Expected result:
```console
$ go run ./sample.go
// ouput
7
```

Got:
```console
$ yaegi ./sample.go
// ouput
3
```

Note: declaring the function as `func x(i int) int` works fine, so I wonder if this is something you just don't want to support.

**Comment by mvertes** [comment]
This is now fixed and working in master, I think from merge of #410
