### ISSUE TITLE
yaegi incorrectly types 1e2 as a non-integer

### ISSUE THREAD

**Issue by kortschak** [containous/yaegi#428]
The following program `sample.go` fails to run with "illegal operand types for '%' operator":

```
func main() {
	i := 100
	if i%1e2 == 0 {
		println(i)
	}
}
```

Expected result:
```console
$ go run ./sample.go
100
```

Got:
```console
$ yaegi ./sample.go
sample.go:5:5: illegal operand types for '%' operator
```

The code with `1e2` replaced by `100` works as expected.

**Comment by mvertes** [comment]
And how strange that: 

```go
func main() { println(100 % 1e2) }
```

fails under `go run`  (same error as yaegi), but

```go
func main() { i := 100; println(i % 1e2)  } 
```

is accepted by the compiler (or even `i % 100.0`) !

Anyway, the spirit of untyped literal numbers is to be convertible to `int` if the decimal part is zero, so I will fix yaegi (and probably file an issue to golang)
