### ISSUE TITLE
Can't import external libraries?

### ISSUE THREAD

**Issue by ashneverdawn** [containous/yaegi#469]
The following program `sample.go` triggers a panic:

```
package foo
import "github.com/ojrac/opensimplex-go"
```

Expected result:
```
no error
```

Got:
```
import "github.com/ojrac/opensimplex-go" error: unable to find source related to: "github.com/ojrac/opensimplex-go"
```

I haven't see any special instructions in the docs on importing external libs. If I try it normally I get this error. What am I missing?
Thanks.

**Comment by mvertes** [comment]
It's true that instructions for importing external libraries are missing in the documentation.

To be imported, external libraries must be first installed manually with the usual shell command
```console
go get github.com/ojrac/opensimplex-go
```
which installs the package and its dependencies in the GOPATH. It will be then visible by `yaegi` for the import command.

The use of Go modules or are not supported yet.

**Comment by mvertes** [comment]
It's also possible to re-build an interpreter containing a pre-compiled library and its wrapper (generated by `goexports`), so the package can be imported without the overhead of interpretation, as it is done for the standard library packages in yaegi.

**Comment by g3rzi** [comment]
> It's also possible to re-build an interpreter containing a pre-compiled library and its wrapper (generated by `goexports`), so the package can be imported without the overhead of interpretation, as it is done for the standard library packages in yaegi.

I tried it but  I received an error:  
```
C:\Users\user1\go\src\gosploit>goexports github.com/tidwall/pretty
2020/06/01 18:20:16 failed to format source: 7:10: expected ';', found ':' (and 3 more errors): // Code generated by 'goexports github.com/tidwall/pretty'. DO NOT EDIT.



// +build go1.13,!go1.14

package C:\Users\user1\go\src\myproj1

import (
        "github.com/tidwall/pretty"
        "reflect"
)

func init() {
        Symbols["github.com/tidwall/pretty"] = map[string]reflect.Value{
                // function, constant and variable definitions
                "Color": reflect.ValueOf(pretty.Color),
                        "DefaultOptions": reflect.ValueOf(&pretty.DefaultOptions).Elem(),
                        "Pretty": reflect.ValueOf(pretty.Pretty),
                        "PrettyOptions": reflect.ValueOf(pretty.PrettyOptions),
                        "TerminalStyle": reflect.ValueOf(&pretty.TerminalStyle).Elem(),
                        "Ugly": reflect.ValueOf(pretty.Ugly),
                        "UglyInPlace": reflect.ValueOf(pretty.UglyInPlace),

                // type definitions
                "Options": reflect.ValueOf((*pretty.Options)(nil)),
                "Style": reflect.ValueOf((*pretty.Style)(nil)),

        }
}
```
