### ISSUE TITLE
Missing type analysis for landExpr. Wrong cfg analysis for landExpr.

### ISSUE THREAD

**Issue by dusmart** [containous/yaegi#517]
The following program `sample.go` triggers a wrong result:

```go
package main
type Fromage struct {
	Done bool
}

func main() {
	a := Fromage{
		true,
	}

	println( a.Done && true )
}
```

Expected result:
```console
$ go run ./sample.go
true
```

Got:
```console
$ yaegi ./sample.go
false
```

Function `deref` and `getIndexSeq` as well as `getPtrIndexSeq` are involved. I'm sure that there are lots of similar code blocks that need to be fixed which you can search by keyword `if n.fnext != nil`. 

Thanks for your great project!

**Comment by dusmart** [comment]
It seems that I misunderstand `fnext`.  Maybe we just need to change `case landExpr` part in `cfg.go`.

**Comment by mvertes** [comment]
Yes, support of ` landExpr` in type analysis is missing, it has to be added first, i.e the following test has to pass:
```go
a := true && true
```
Then the correction of the bug itself will be easy.

**Comment by mvertes** [comment]
Look at `nodeType()` in `type.go`, this is where the case is missing.

**Comment by dusmart** [comment]
Actually speaking, It's hard to understand these codes. Sorry for providing wrong solutions. Thanks for your help.

**Comment by dusmart** [comment]
Are there any books for understanding those concepts such as tnext/fnext?

**Comment by dusmart** [comment]
> Look at `nodeType()` in `type.go`, this is where the case is missing.

This solved `a := true && true`. While `sample.go` still gives the wrong answer.

**Comment by mvertes** [comment]
I'm afraid the particular concept of fnext tnext (true and false branch) is not described in any book. It's a process of mine, consisting of wiring the Control Flow Graph in the Abstract Syntax Tree, and it leads to important simplifications and optimizations at run (much less indirections and tests than usual byte code machines).
