### ISSUE TITLE
Question: export main package functions ?

### ISSUE THREAD

**Issue by bombjackm** [containous/yaegi#523]
Hi, Is it possible to export functions from the main package ?
The example below doesn't work.

package main

import (
	"reflect"

	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

func Hello() {
	println("Hello")
}

func main() {
	i := interp.New(interp.Options{})

	i.Use(stdlib.Symbols)

	//This will make a 'custom' lib  available that can be imported and contains your Data struct
	custom := make(map[string]map[string]reflect.Value)
	custom["main"] = make(map[string]reflect.Value)
	custom["main"]["Hello"] = reflect.ValueOf(Hello)
	i.Use(custom)

	_, err = i.Eval(`Hello()`)
	if err != nil {
		panic(err)
	}
}

**Comment by bombjackm** [comment]
sorry I found that I can use "import . main" to achieve my goal.

**Comment by xyzgogo** [comment]
@bombjackm  I have the same problem. My code is :
```go
func Hello() {
	println("Hello")
}

func main() {
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	custom := make(map[string]map[string]reflect.Value)
	custom["main"] = make(map[string]reflect.Value)
	custom["main"]["Hello"] = reflect.ValueOf(Hello)
	i.Use(custom)

	_, err := i.Eval(`import . "main"`)
	if err != nil {
		panic(err)
	}
	_, err = i.Eval(`Hello()`)
	if err != nil {
		panic(err)
	}
}
```
But it can't work. Can you give the full code ?
