### ISSUE TITLE
Operator += bug

### ISSUE THREAD

**Issue by leonxiong516** [containous/yaegi#541]
The following program `sample.go` triggers an unexpected result:

```go
package main

func main() {
	str := "part1"
	str += fmt.Sprintf("%s", "part2")
	fmt.Println(str)
}
```

Expected result:
```console
$ go run ./sample.go
part1part2
```

Got:
```console
$ yaegi ./sample.go
part2
```

**Comment by mvertes** [comment]
It's strange that `fmt.Sprintf("%s", "part2")` doesn't result in `"part2"` in regular Go.

What I see on `master` is:
```console
$ go run ./sample.go
part2
```
Normal to me, but different from you.

and
```console
$ yaegi ./sample.go
part2
```

Same as you, and expected. I do not have problem with this test case.

**Comment by leonxiong516** [comment]
Sorry！ I'm wrong. I've updated the bug description

**Comment by mvertes** [comment]
Ok, bug confirmed!
