### ISSUE TITLE
We should set rVal in `run` part instead of `cfg`. Here is a `sample.go` which gives wrong result.

### ISSUE THREAD

**Issue by dusmart** [containous/yaegi#553]
We set values in `cfg` part which will not be executed actually. In part `*ast.ParenExpr` of `ast.go`, we choose `nop` op as our node's action which should be replaced by some action like `aNot`. Here is a solution to this problem:

1. Set `st.push(addChild(&root, anc, pos, parenExpr, aParen), nod)` in `ast.go`
2. Add `aParen` node action in `ast.go`
3. Add buildin function `paren` for `aParen` in `run.go`
4. define function `paren` like `not`
```
func paren(n *node) {
	dest := genValue(n)
	value := genValue(n.lastChild())
	tnext := getExec(n.tnext)
	i := n.findex

	if n.fnext != nil {
		fnext := getExec(n.fnext)
		n.exec = func(f *frame) bltn {
			if !value(f).Bool() {
				f.data[i].SetBool(false)
				return fnext
			}
			f.data[i].SetBool(true)
			return tnext
		}
	} else {
		n.exec = func(f *frame) bltn {
			dest(f).SetBool(value(f).Bool())
			return tnext
		}
	}
}
```

The following program `sample.go` gives a wrong result:

```go
package main

func main() {
    a := 0
    if ( false) {
        a = 1
    } else {
        a = -1
    }
    println(a)
}
```

Expected result:
```console
$ go run ./sample.go
-1
```

Got:
```console
$ yaegi ./sample.go
1
```

**Comment by dusmart** [comment]
If this solution is accepted, we should check all other `rVal` assigning operation in `cfg`'s postOrder analysis procedure.

**Comment by dusmart** [comment]
Maybe we can solve the problem using` rVal` with the type of pointer.

**Comment by mvertes** [comment]
Thanks for your useful report. It shows that conditional statements are not well evaluated for hard coded constant expressions.

The solution is not to displace the evaluation of constant value in `rval` at execution (in `run.go`), but the opposite, to use the `rval` (that is the constant value known at compile time) to build directly the correct control flow graph (and bypass entirely the test and useless branch at execution). This part is actually missing, thus the bug.

For information, the purpose of `rval` is to store constant values that can (and must be) computed at compile time (so in `cfg.go`), versus other dynamic values which are computed during execution and live in stack frame.

I'm preparing the fix, which is likely to be quite different of what you proposed. Thanks anyway for your efforts and analysis.

**Comment by dusmart** [comment]
This didn't solve the problem of `if (cond) {}` where parenthesis appear after if.

**Comment by dusmart** [comment]
While the value of a `parenExpr` can not be determined before running, `sample.go` in this post will always give `1` instead of `-1`.

**Comment by dusmart** [comment]
Thank you for your interpretation of `rVal` and all other things. It's very useful for me to understand this repo.

**Comment by dusmart** [comment]
In my opinion, the `aParen` action is necessary for expression `parenExpr`. Here is another `sample.go` which gives a wrong result.

```
package main

func main() {
    a := 0
    b := false
    if (b) {
        a = 1
    } else {
        a = -1
    }
    println(a)
}
```

**Comment by dusmart** [comment]
`parenExpr` is the same as `identityExpr`.  Some action for this expression to assign the dynamic value of expression inside the parenthesis to `parenNode` is needed.

**Comment by mvertes** [comment]
You're right. I opened a new issue #564 with the above example to track this problem.
