### ISSUE TITLE
Support Go 1.12 and Go 1.13

### ISSUE THREAD

**Issue by GuigsEvt** [containous/yaegi#554]
Hi, 

I encountered issue on the Golang version. When trying to use "/yaegi/stdlib" it does not work on version 1.12 only 1.13 and 1.14. 

You should mention it on the README instead of saying compatible version 1.12 and 1.13. 

Cheers

**Comment by ldez** [comment]
Hello,

We support the same versions as the Go Team support, so currently 1.13 and 1.14.

I forgot to update the readme, I will fix that.

Thank you.
