### ISSUE TITLE
 json operations generate bugs

### ISSUE THREAD

**Issue by derivaro** [containous/yaegi#590]
triggers a panic:
 json.Unmarshal

**Comment by mvertes** [comment]
Could you more details. Is it related to #588 ?

**Comment by derivaro** [comment]
I Marc, maybe it the way i implement, 
This is the string code i store in an array of code for example:

stcode := ` 
	import (
		"crypto/tls"
		"encoding/json"
		"fmt"
		"io/ioutil"
		"net/http"
		"time"
		"strconv"
	)
	

	func simple(url string, uri2 string, uri3 string, token string, timout int) string {
		return "Hollo tete"
//test interpreter
	}


	func getRed1(url string, uri2 string, uri3 string, token string, timout int) string {

		tr := &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		}
		client := &http.Client{Transport: tr, Timeout: time.Duration(timout*1000) * time.Millisecond}
		// Create a new request using http
		req, _ := http.NewRequest("GET", url, nil)
	
		// add authorization header to the req
		req.Header.Add("Authorization", token)
		req.Header.Add("x-auth-token", token)
		req.Header.Add("Content-Type", "application/json")
	
		r2, err := client.Do(req)
		if err != nil {
			fmt.Println("err de recup: " + err.Error())
			return ""
		}
		defer r2.Body.Close()
		content, _ := ioutil.ReadAll(r2.Body)
	
      //  return string(content)
	//--------------------------------
	  var qq2 map[string]interface{}
	  qq2 = make(map[string]interface{})
	 
	    if err2 := json.Unmarshal(content, &qq2); err2 != nil {
	  	  return "error with q2"
	    }
	  return qq2["APIKey"].(string)
//
//return "ouf"

	}

// and other and other things that works well...

`
------------------------------------------------------------------------
 inside func getRed1, the only thing that give me troubles is this part :

	  var qq2 map[string]interface{} // i use generic map
	  qq2 = make(map[string]interface{})
	 
	    if err2 := json.Unmarshal(content, &qq2); err2 != nil {
	  	  return "error with q2"  //but the code goes panic with unmarshal
	    }
	  return qq2["APIKey"].(string)

The way i call  the function :
-----------------------------
i use a generic func (FnStringApi) that map the func in the interpreter, it works well, i use it to build dynamics micro web services (its very very usefull), but when i try to unmarshall with generic interface map it send me to panic statement...


	js1 := FnStringApi("APis", "getRed1")(rw.FI[rs.C["api1"]], "", "", rw.FI[rs.C["apitoken"]], timut)
				//js1 := getRedash1(rw.FI[rs.C["api1"]], "", "", rw.FI[rs.C["apitoken"]], timut)
       fmt.Println(js1)




func FnStringApi(pkg string, fn string) func(string, string, string, string, int) string {
	var fnullApi = func(string, string, string, string, int) string {
		return "Error in " + pkg + "." + fn
	}
// pRogs[pkg] is a map that store the prog with the package as name
	if _, ok := pRogs[pkg]; ok {
		ip := interp.New(interp.Options{})
		ip.Use(stdlib.Symbols)
		_, err := ip.Eval(ucry(pRogs[pkg].src))
		if err != nil {
			fmt.Println("Can t get in interpreter " + ip.Name + " " + err.Error())
			return nil
		}

		v, err := ip.Eval(fn)
		if err != nil {
			fmt.Println(" pb de recup de fonction")
			return fnullApi
		}

		i := v.Interface().(func(string, string, string, string, int) string)
		return i

	}
	return fnullApi

}

It s difficult to reproduce the context, don t waste too much time with that if you are sure that it works , more chances that i missed something inside my plant !

Rgds
Antoine

**Comment by derivaro** [comment]
Ok, i made another simple test and it s work perfectly ,
it was because i didn't declare all the imports... grrrr
thx !!!
