### ISSUE TITLE
CLI tool for v0.8.5 no longer accepts input via pipes

### ISSUE THREAD

**Issue by alebcay** [containous/yaegi#636]
In versions prior to v0.8.5, piping input into the CLI tool would allow for the input to be evaluated. Starting in v0.8.5, this behavior has changed, and I could not find any documentation indicating that this was an intentional change.

Expected result:
```console
$ echo "3 + 1" | yaegi
4
```

Got:
```console
$ echo "3 + 1" | yaegi
// no output
```
I observed this behavior after using both official (via GitHub releases) and self-built binaries from v0.8.4 and v0.8.5 in Linux amd64 and Darwin amd64.

**Comment by mvertes** [comment]
The input is still evaluated, but silently.The previous behavior will be restored soon. In the meantime, you can run:
```console
$ echo 'println(3 + 1)' | yaegi
4
```

**Comment by alebcay** [comment]
I see, thanks.
