### ISSUE TITLE
Unexpected behavior with fmt.Printf's %T verb

### ISSUE THREAD

**Issue by Ullaakut** [containous/yaegi#654]
The following program `sample.go` does not provide the same output as `go run` does:

```go
package main

import (
	"fmt"
)

type S struct{}

func (s S) f() {
	fmt.Println("hello")
}

type I interface {
	f()
}

func printType(i I) {
	fmt.Printf("%T\n", i)
	if s, ok := i.(S); ok {
		s.f()
	}
}

func main() {
	printType(S{})
}
```

Expected result:
```console
$ go run ./sample.go
main.S
hello
```

Got:
```console
$ yaegi ./sample.go
struct {}
hello
```

The call to `fmt.Printf`'s `%T` verb does not panic but it outputs `struct{}` instead of the type that was defined in this package, `main.S`.

**Comment by mvertes** [comment]
As `reflect` doesn't allow the creation of named types visible from the runtime, there is not an easy way to address this issue. This limitation is documented here: https://github.com/containous/yaegi#limitations

**Comment by Ullaakut** [comment]
Ah, my bad, I missed that one!
