### ISSUE TITLE
semicolon or shortcut key to indicate the end of statement in repl mode

### ISSUE THREAD

**Issue by inVisement** [containous/yaegi#713]
#### Proposal

Add a shortcut to end the current line/statement in repl (ex: ctrl+q or semicolon to imply the statement is finished)

#### Background

It happens a lot that a wrong statement is given to the repl interpreter such as x := []{"this"} and the only way to let repl knows we are finished is to exit the interpreter. It would be very helpful if there was a character (like semicolon) or shortcut (like ctrl+q) to let repl know we are done and execute this statement (and probably return error)

#### Workarounds

![image](https://user-images.githubusercontent.com/38025828/85385277-f4c92980-b4f6-11ea-9e7a-9dbed193e00e.png)

**Comment by mvertes** [comment]
We are already supposed to catch interrupt signal (Ctrl-C) when in REPL and cancel the current Eval without killing the process. I think this part is buggy right now, we will look at it.
