### ISSUE TITLE
method receiver is incorrectly recursive

### ISSUE THREAD

**Issue by nrwiersma** [containous/yaegi#716]
The following program `sample.go` triggers a panic:

```go
package main

type Client struct {
	freeConns map[string][]*conn
}

func (c *Client) getConn(addr string) *conn {
	cns, ok := c.freeConns[addr]
	if !ok || len(cns) == 0 {
		return nil
	}

	return cns[0]
}

type conn struct {
	c *Client
}

func main() {
	c := &Client{
		freeConns: map[string][]*conn{},
	}
	c.freeConns["test"] = append(c.freeConns["test"], &conn{c: c})

	cn := c.getConn("test")
	println(cn != nil)
}
```

Expected result:
```console
$ go run ./sample.go
true
```

Got:
```console
$ yaegi ./sample.go
_test/test1.go:22:14: panic
reflect.Set: value of type *struct { XfreeConns map[string][]*struct { Xc *struct { XfreeConns map[string][]*interface {} } } } is not assignable to type *struct { XfreeConns map[string][]*interface {} }
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0001d4a00, 0x40)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc000237de8)
	/Users/nrwiersma/Go/src/github.com/containous/yaegi/interp/interp.go:333 +0xbc
panic(0x18a6b40, 0xc000225360)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc0001b75e0, 0xc000331200)
	/Users/nrwiersma/Go/src/github.com/containous/yaegi/interp/run.go:115 +0x20c
panic(0x18a6b40, 0xc000225360)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969 +0x166
reflect.Value.assignTo(0xc00032c640, 0xc000198a18, 0x196, 0x19da746, 0xb, 0xc00032c580, 0x0, 0x1014174, 0xc000237b88, 0x10b0701)
	/usr/local/Cellar/go/1.14.4/libexec/src/reflect/value.go:2403 +0x426
reflect.Value.Set(0xc00032c580, 0xc0001989a8, 0x196, 0xc00032c640, 0xc000198a18, 0x196)
	/usr/local/Cellar/go/1.14.4/libexec/src/reflect/value.go:1532 +0xbd
github.com/containous/yaegi/interp.doCompositeSparse.func1(0xc0001b75e0, 0xc00032c800)
	/Users/nrwiersma/Go/src/github.com/containous/yaegi/interp/run.go:2004 +0x13d
github.com/containous/yaegi/interp.runCfg(0xc000331200, 0xc0001b75e0)
	/Users/nrwiersma/Go/src/github.com/containous/yaegi/interp/run.go:121 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc00023e1a0, 0xc000330500, 0xc0001b7540)
	/Users/nrwiersma/Go/src/github.com/containous/yaegi/interp/run.go:99 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc00023e1a0, 0xc0002da340, 0x19b, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/nrwiersma/Go/src/github.com/containous/yaegi/interp/interp.go:409 +0x52b
main.main()
	/Users/nrwiersma/Go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:149 +0x5d8
```

**Comment by nrwiersma** [comment]
**Example Case:**
```go
type Type struct {
	a map[string][]*A
}

type A struct {
	b *Type
}
```

From the perspective of each type, each is recursive in its own way, meaning a conversion from one form of recursion to another is difficult if not impossible.

**Possible Solution:**
Instead of finding the point of recursion and replacing it with an `interface{}`, instead we looks for all intermediate structs in a recursive path, replacing each with an `interface{}`. This would result in the following `rtype`:

```go
type Type struct {
	a map[string][]*interface{}
}

type A struct {
	b *interface{}
}
```

This should allow us to have an arbitrarily deep recursive path, and still be able to handle the struct conversions in a couple key areas.

**Field Recursive Cases:**
Type			: Type -> []:map[]:*A -> Type
*Type			: Type -> *Type
[]Type			: Type -> []Type
[]*Type			: Type -> []*Type
map[x]Type		: Type -> map[x]Type
map[x]*Type		: Type -> map[x]*Type

The current refType detection can detect all of the above except the first, which could
pose an issue. We would need to look into this case.

Wether the `interface{}` stores a `struct` or `valueInterface` should not make a huge difference to the proposed solution.

@mvertes Thoughts?

**Comment by nrwiersma** [comment]
It should probably be noted that the field recursive cases become arbitrarily deep after what is listed, and it is impractical to try and detect each case individually. We like need a more generic `isRecursiveType` that can detect these cases, and generic `genValueRecursiveInterface` and `genValueRecursiveInterfaceValue` methods to handle this.

**Comment by nrwiersma** [comment]
It occurs to me that we will have an issue with `refType` with this method. When `t.val` is set to `interf`, it will cause some structs to get the wrong `rtype`. We can deal with this by cloning the type in this case.

**Comment by mvertes** [comment]
This approach sounds good. It's not so far from the current implementation, which is a first step in this direction. We need a robust criteria to trigger recursive processing in all possible combinations, either for set or get values. Having a `*interface{}` value plus a recursive flag on the field struct is maybe ok.

**Comment by nrwiersma** [comment]
If we clone the type before setting the rtype to interface{}, we will more easily be able to detect the recursion.
