### ISSUE TITLE
global variable definition seems incorrect

### ISSUE THREAD

**Issue by topxeq** [containous/yaegi#730]
The following program `sample.go` triggers a panic with the latest version:

```go
package main

var optionsG map[string]string = nil

var roundG = 30

func main() {

	dummy := roundG

	roundG = dummy + 1
	println(roundG)

	println(optionsG)
}


```

Expected result:
```console
$ go run ./sample.go
30
nil
```

Got:
```console
$ yaegi ./sample.go
9:2: panic
failed to run script(sample.go): reflect: call of reflect.flag.mustBeAssignable on zero Value

```

**Comment by mvertes** [comment]
Thanks for this report.

What happened here is that the `dummy + 1` operation attempted to write its result to the wrong frame location, due to a frame indirection level not correctly updated. The PR #733 fixes that.
