### ISSUE TITLE
Support Explicit Passing of Stdout/Stderr to Yaegi

### ISSUE THREAD

**Issue by kevinschoon** [containous/yaegi#752]
#### Proposal

Add the ability to explicitly pass an `io.Writer` to the Yeagi interpreter so that terminal output from the interpreted code could be avoided. Here is some example code with my proposed change:

```go
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

const script = `
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Fprintln(os.Stdout, "hello from interp stdout")
	fmt.Fprintln(os.Stderr, "hello from interp stderr")
}
`

func main() {
	stdout := bytes.NewBuffer(nil)
	stderr := bytes.NewBuffer(nil)
        // if no writers are passed the interpreter should fallback
        // to writing to stdout/stderr of the calling process.
	i := interp.New(interp.Options{
		Stdout: stdout, // new functionality here
		Stderr: stderr,
	})
	i.Use(stdlib.Symbols)
	i.Eval(script)
	fmt.Fprintln(os.Stdout, "hello from main stdout")
	fmt.Fprintln(os.Stderr, "hello from main stderr")
}
```

This was originally opened in https://github.com/containous/yaegi/issues/728 by @g3rzi however they closed the issue with a workaround but I felt it was still valuable.

Thanks for your work on this great project!

#### Background

I am writing a [tool](https://github.com/kevinschoon/qviz) to do data visualization that leverages Yaegi and I would like to be able to explicitly control the stdout/stderr of evaluated programs so I can display logs in a UI.

#### Workarounds

@mpl mentions a workaround here: https://github.com/containous/yaegi/blob/4f3481b55c207b933902314a7eac6aee88ed82d6/example/pkg/pkg_test.go#L109-L135

**Comment by kevinschoon** [comment]
After posting my issue above I realized there is a slightly more convenient way of controlling stdout/stdout by modifying the `stdlib` values. This has the disadvantage of mutating globals however.

```go
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"reflect"

	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

const script = `
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Fprintln(os.Stdout, "hello from interp stdout")
	fmt.Fprintln(os.Stderr, "hello from interp stderr")
}
`

func main() {
	stdout, _ := ioutil.TempFile("/tmp", "stdout")
	stderr, _ := ioutil.TempFile("/tmp", "stderr")
	i := interp.New(interp.Options{})
	stdlib.Symbols["os"]["Stdout"] = reflect.ValueOf(stdout)
	stdlib.Symbols["os"]["Stderr"] = reflect.ValueOf(stderr)
	i.Use(stdlib.Symbols)
	i.Eval(script)
	fmt.Fprintln(os.Stdout, "hello from main stdout")
	fmt.Fprintln(os.Stderr, "hello from main stderr")
}
```

**Comment by mvertes** [comment]
Thanks for this proposal. We will add `output` and `error` `io.Writers` to the `Option` struct. We have also to change the `REPL` API to set the error stream which is missing right now.

**Comment by kevinschoon** [comment]
Thanks @mvertes, let me know how I can help!

**Comment by g3rzi** [comment]
Is there a way you can support a case where the golang code takes time and print every couple of seconds and redirect it while it still working?  
Because currently, in such a case, Yaegi is waiting for the code to finish running.  

In the following example I tried to redirect the STDOUT but it doesn't work because Yaegi waits for `Eval()` to finish.  
Example:  
```go
package main

import (
	"bytes"
	"fmt"
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
	"io"
	"os"
)

const payload = `
package main

import (
	"fmt"
	"time"
)

func main() {

	for i := 0; i < 50; i++ {
		time.Sleep(2 * time.Second)
		fmt.Printf("hello number: %d\n", i)
	}
}
`

func main(){
	var err error
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	stdout := os.Stdout
	defer func() { os.Stdout = stdout }()
	pr, pw, err := os.Pipe()
	if err != nil {

	}

	os.Stdout = pw
	_, err = i.Eval(payload)

	var buf bytes.Buffer
	errC := make(chan error)
	go func() {
		_, err := io.Copy(&buf, pr)
		errC <- err
	}()


	if err := pw.Close(); err != nil {

	}
	if err := <-errC; err != nil {

	}
	msg := buf.String()

	fmt.Println(msg)

	if err != nil {
		panic(err)
	}
}
```
