### ISSUE TITLE
Vendoring management

### ISSUE THREAD

**Issue by Trois-Six** [containous/yaegi#758]
Hi,

When you need vendors in a subfolder inside your code, yaegi doesn't find them. You have to copy the complete vendor folder to the subfolder (a symlink doesn't work).

Pierre

**Comment by mpl** [comment]
Hi,

This might be fixed by https://github.com/containous/yaegi/commit/4f3481b55c207b933902314a7eac6aee88ed82d6 , which should be in the latest version (0.8.11).

What version of yaegi are you running?

**Comment by Trois-Six** [comment]
0.8.11

**Comment by Trois-Six** [comment]
I tried with bc2b224bae1b300270b605e364d20a311c603bef and I have the same problem.
Example to explain the problem: https://github.com/Trois-Six/yaegitest
