### ISSUE TITLE
redeclared struct

### ISSUE THREAD

**Issue by yuanyangen** [containous/yaegi#778]
The following program `sample.go` triggers a panic:

yaegi version: v0.8.9 -  v0.8.12 

```go
package yaegi

import (
	"github.com/containous/yaegi/interp"
	"testing"
)

const src = `package main

import (
)

type GetHistoryLocRsp struct { 
    DailyItems []DailyItem  
}

type DailyItem struct { 
    Timestamp int64    
}
`

func TestM(tt *testing.T) {
	i := interp.New(interp.Options{})
	_, err := i.Eval(src)
	if err != nil {
		panic(err)
	}
}
```

Expected result:
```console
the code will run without panic

```

Got:
```console
panic：

panic: 10:6: DailyItem redeclared in this block [recovered]
	panic: 10:6: DailyItem redeclared in this block

goroutine 270 [running]:
testing.tRunner.func1.1(0x1b55740, 0xc00017bae0)
	/home/yuanyangen/.install/go/src/testing/testing.go:940 +0x4dc
testing.tRunner.func1(0xc0003cc900)
	/home/yuanyangen/.install/go/src/testing/testing.go:943 +0x317
panic(0x1b55740, 0xc00017bae0)
	/home/yuanyangen/.install/go/src/runtime/panic.go:975 +0x41b
code.byted.org/hotsoon/func_core/executor/yaegi.TestM(0xc0003cc900)
	/home/yuanyangen/HomeData/go/func/func_core/executor/yaegi/yaegi_raw_test.go:26 +0x10e
testing.tRunner(0xc0003cc900, 0x1c72670)
	/home/yuanyangen/.install/go/src/testing/testing.go:991 +0x18a
created by testing.(*T).Run
	/home/yuanyangen/.install/go/src/testing/testing.go:1042 +0x660
```

**Comment by mpl** [comment]
to be fair, the code in `src` is invalid anyway, because it lacks a main func(). So `go run` would fail to run it in any case. But the false positive about DailyItem is indeed a bug.

**Comment by yuanyangen** [comment]
> to be fair, the code in `src` is invalid anyway, because it lacks a main func(). So `go run` would fail to run it in any case. But the false positive about DailyItem is indeed a bug.
thanks for your repley. 
 this `src` lack of main funciton  just because I define some struct in a single file ( this file is named as model ), and this seems like a normal operation.

**Comment by yuanyangen** [comment]
> @yuanyangen as a workaround for now, if you move the code in `src` to a .go file, and set `i.Name` to the location of the source .go file, you should be able to dodge the panic.

this woks

**Comment by mpl** [comment]
btw, this issue is closely related to #731 , but not marking as duplicate since it is a somewhat simpler and more limited case, and as such we might be able to work-around it, without needing the more drastic changes that are likely required for fixing #731 .
