### ISSUE TITLE
How to pass arguments to the interpreter function Eval(..)?

### ISSUE THREAD

**Issue by g3rzi** [containous/yaegi#788]
How can I pass arguments to code I send to Yaegi Go's interpreter?

I have the following code:
```go
package main

import (
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

const payload = `
package main

import (
	"fmt"
	"os"
)

func main() {
	argsWithProg := os.Args
	var args string
	if len(argsWithProg) < 2 {
		args = "empty"
	} else {
		args = argsWithProg[1]
	}

	fmt.Printf("Hellow World: %s\n", args)
}
`

func main(){

	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	_, err := i.Eval(payload)
	if err != nil {
		panic(err)
	}
}
```

It send this code to Yaegi:
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	argsWithProg := os.Args
	var args string
	if len(argsWithProg) < 2 {
		args = "empty"
	} else {
		args = argsWithProg[1]
	}

	fmt.Printf("Hellow World: %s\n", args)
}
```

This code can get argument.

Expected result:
```console
$ go run ./sample.go baba
// Hellow World: baba
```

But how can I pass arguments to `i.Eval(payload)` ?

**Comment by g3rzi** [comment]
I have a workaround for that, I will declare a global argument in the `i.Eval(..)` before running the code. But is there other way to do it?

```go
package main

import (
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

const payload = `
package main

import (
	"fmt"
	"os"
)

func main() {

	var args string
	if globalVar == "" {
		args = "empty"
	} else {
		args = globalVar
	}


	fmt.Printf("Hellow World: %s\n", args)
}
`

func main(){
        var err error
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)
        
        _, err = i.Eval(`globalVar := "global var"`)
	_, err = i.Eval(payload)
	if err != nil {
		panic(err)
	}
}

```

**Comment by mpl** [comment]
Hello,

there are at least two ways you could achieve that.

1) If we assume you have no control over payload, and it has to stay a main as it would have been written as a Go main program, then the work-around you found is close enough. You should be able to simplify it a bit, by directly setting os.Args, since it is an exported variable, and therefore you shouldn't even need the globalVar you used. But as you probably guessed , this is pretty gross.

2) If you can rewrite the payload, you can make it more suitable to be called with Eval, e.g.:

```
package main

import (
	"log"

	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

const payload = `
package main

import (
	"fmt"
)

func mainfunc(args []interface{}) {
	args = append([]interface{}{"Hello World"}, args...)
	fmt.Println(args...)
}
`

func main() {

	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	_, err := i.Eval(payload)
	if err != nil {
		log.Fatal(err)
	}
	_, err = i.Eval(`mainfunc([]interface{}{"this", "is", "a", "message", "to", "the", "world"})`)
	if err != nil {
		log.Fatal(err)
	}
}
```

An even better way, would be to make mainfunc a generator, i.e. it would return the func that is to be called.
then you could do something like (I haven't tested that yet):

```
val, err := i.Eval(`mainfunc`)
...
hello := val.Interface().(func())
hello("this", "is", "a", "message", "to", "the", "world")
```
which would allow you to rely even more on the Go type system checks.

**Comment by g3rzi** [comment]
Cool, I thought when you run the first main function like that:
```go
_, err := i.Eval(payload)    // will run the program
....
_, err = i.Eval(`mainfunc([]interface{}{"this", "is", "a", "message", "to", "the", "world"})`)
```

The first `Eval` will be called and run the program, so if my program was:
```
const payload = `
package main

import (
	"fmt"
)

func mainfunc(args []interface{}) {
        fmt.Println("MyTest1")
	args = append([]interface{}{"Hello World"}, args...)
	fmt.Println(args...)
}
`
```

It thought it will call twice to `fmt.Println("MyTest1")` but it didn't happen, any idea why (it called it only one time)?


I tried your last variation, it didn't work because of syntax so I changed it a bit:
```go

const payload5 = `
package main

import (
	"fmt"
)

func mainfunc(args []interface{}) {
	//args = append([]interface{}{"Hello World"}, args...)
	fmt.Println(args[0])
	fmt.Println("a")
}

`

func main(){
	var err error
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	val, err := i.Eval(payload5)
	hello := val.Interface().(func([]interface{}))

	hello([]interface{}{"blabla"})
	if err != nil {
		panic(err)
	}
}

```

With the error:
```
panic: interface conversion: interface {} is *interface {}, not func([]interface {})
```

I am not sure how it wants me to provide the arguments to the `hello` function.


I will use your suggestion with the `[]interface{}` idea, this looks cleaner. Thanks :)

**Comment by mpl** [comment]
> Cool, I thought when you run the first main function like that:
> 
> ```go
> _, err := i.Eval(payload)    // will run the program
> ....
> _, err = i.Eval(`mainfunc([]interface{}{"this", "is", "a", "message", "to", "the", "world"})`)
> ```
> 
> The first `Eval` will be called and run the program, so if my program was:
> 
> ```
> const payload = `
> package main
> 
> import (
> 	"fmt"
> )
> 
> func mainfunc(args []interface{}) {
>         fmt.Println("MyTest1")
> 	args = append([]interface{}{"Hello World"}, args...)
> 	fmt.Println(args...)
> }
> `
> ```
> 
> It thought it will call twice to `fmt.Println("MyTest1")` but it didn't happen, any idea why (it called it only one time)?

Well, there's nothing in payload that _calls_ mainfunc, so if you only Eval payload, mainfunc itself is never run. It really is no different than if you put payload in a .go file and tried to `go run` it, you wouldn't see mainfunc being run either. (Well, it wouldn't work at all anyway, since I believe it's forbidden to have a package main without a main func, but that's beside the point).

**Comment by g3rzi** [comment]
okay I see, if I would call it just `main` it wouldn't work as expected.
Thank you for you answer, I will try the interface solution, looks like a good one. Thanks :)
