### ISSUE TITLE
Question: Can you call go function from the script?

### ISSUE THREAD

**Issue by onthegit** [containous/yaegi#803]
Can you call go function from the script? Do you need to first register the go function so that you can call it from yaegi?

Can you call the golang function as goroutine from yaegi?

**Comment by mpl** [comment]
> Can you call go function from the script? Do you need to first register the go function so that you can call it from yaegi?

If you're asking whether a function from the Go standard library can be called, then you indeed need to first include the pre-compiled symbols of the standard library with the Use method of the Interpreter. For example, here is how to use `Println` from the `fmt` package of the standard library:

https://github.com/containous/yaegi#as-an-embedded-interpreter

> Can you call the golang function as goroutine from yaegi?

Yes, as far as I know goroutines are supported as well.

**Comment by onthegit** [comment]
I was thinking to call function that you define yourself, not from the standard library?
Can you do that and then return the value to the call yaegi code?

**Comment by mpl** [comment]
> I was thinking to call function that you define yourself, not from the standard library?
> Can you do that and then return the value to the calling yaegi code?

Yes.
https://github.com/containous/yaegi#as-a-dynamic-extension-framework

**Comment by onthegit** [comment]
Hi, thanks for the reply.
