### ISSUE TITLE
Way to check if function is accesible from yaegi?

### ISSUE THREAD

**Issue by onthegit** [containous/yaegi#804]
Hello,
thanks for the nice project. Because the script that yaegi evaluates could be dynamic, how can we check if a function exists before using it in yaegi?

**Comment by mpl** [comment]
Do you mean when you're running yaegi in interactive (REPL) mode, or when you are calling Eval?

**Comment by onthegit** [comment]
When you are calling Eval? How can we check whether the function is registered in Symbols?

**Comment by mpl** [comment]
I don't understand what you're trying to do. How would you end up in a situation where you don't know whether a symbol is defined? As the caller, you're in control of everything you define and import, so you should have full knowledge. Can you describe a concrete case for the situation please?

In any case, I don't think there's anything in the API that directly exposes the symbols known to the interpreter, so I think the easiest solution is to simply Eval a bit of code that uses the symbol, and see if you get an error. And if you really need to automate/analyse whether the error is due to the symbol being undefined, then you can parse the error message itself. e.g.:

```go
package main

import (
	"log"
	"strings"

	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

const defineHello = `
	func hello() {
		println("hello")
	}
`

func main() {
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols) // Use binary standard library

//	if _, err := i.Eval(defineHello); err != nil {
//		log.Fatal(err)
//	}

	_, err := i.Eval("if hello != nil {}")
	if err != nil {
		if strings.Contains(err.Error(), "undefined: hello") {
			log.Fatal("NOPE")
		}
		log.Fatal(err)
	}
	if _, err := i.Eval("hello()"); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by onthegit** [comment]
Hello, thanks for your reply. The case would be  when other users put their own scripts to be evaluated that reference custom defined Symbols refercing golang functions. The golang  functions may change while the user's scripts may not get updated so they will end up calling undefined functions.

**Comment by onthegit** [comment]
file ftest.go
e.g:
`package main

import "reflect"

// Symbols s
var Symbols = map[string]map[string]reflect.Value{}


func init() {
	Symbols["ftest"] = map[string]reflect.Value{
		"Test":       reflect.ValueOf(test),
	}
}`

file main.go :
func test() {

	fmt.Println("Hello Test from Yaegi")
}	
func main() {
i := interp.New(interp.Options{})
	var wg sync.WaitGroup
	i.Use(Symbols)
	_, err := i.Eval(`import "ftest")`   
        _, err = i.Eval(`ftest.test()`) //test() could change in the main go code
}`

**Comment by onthegit** [comment]
Can we do something inside yaegi like:
if val, ok := Symbols["foo"]; ok {
    //do something here
}
how to get hold of Symbols?

**Comment by mpl** [comment]
> Can we inside yaegi , do something like:
> if val, ok := Symbols["foo"]; ok {
> //do something here
> }
> how to get hold of Symbols?

As I said above, you can't. The information is in internal maps of the Interpreter, which are not exported, and not accessible through the API.

**Comment by akkuman** [comment]
@onthegit @mpl  I have a relatively hacker approach, via Golang's reflect

```
type Interpreter struct {
	itp *interp.Interpreter
	itpSrcPkg reflect.Value
}

func NewInterpreter(itp *interp.Interpreter) (i *Interpreter) {
	i = new(Interpreter)
	i.itp = itp
	i.itpSrcPkg = reflect.Indirect(reflect.ValueOf(i.itp)).FieldByName("srcPkg")
	return
}

func (i *Interpreter) HasSymbol(pkg, name string) bool {
	imp := i.itpSrcPkg.MapIndex(reflect.ValueOf(pkg))
	if !imp.IsValid() {
		return false
	}
	symbol := imp.MapIndex(reflect.ValueOf(name))
	return symbol.IsValid()
}
```

**Comment by akkuman** [comment]
test example

```go
func TestAccessNoExistsVar(t *testing.T) {
	src := `
	package src

	var (
		a = 1
	)
	`
	i := interp.New(interp.Options{})
	i.Use(exposeSymbols)

	i.Eval(src)
	itp := NewInterpreter(i)
	if !itp.HasSymbol("src1", "b") {
		t.Error("dont has symbol")
	}
	bvar, err := i.Eval("src1.b")
	if err != nil {
		t.Error(err)
	}
	t.Log(bvar)
}
```
