### ISSUE TITLE
stdlib.Symbols is not recognize: "undefined: stdlib.Symbols"

### ISSUE THREAD

**Issue by mydockergit** [containous/yaegi#837]
The following program `sample.go` triggers a panic:

```go
package main

import (
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

func main() {
	i := interp.New(interp.Options{})

	i.Use(stdlib.Symbols)

	_, err := i.Eval(`import "fmt"`)
	if err != nil {
		panic(err)
	}

	_, err = i.Eval(`fmt.Println("Hello Yaegi")`)
	if err != nil {
		panic(err)
	}
}
```

Expected result:
```console
$ go run ./sample.go
Hello Yaegi
```

Got:
```console
$ yaegi ./sample.go
.\main.go:11:8: undefined: stdlib.Symbols
```

It worked for me in the past, I am not sure what happened.

**Comment by ldez** [comment]
Hello,

In the [latest version](https://github.com/containous/yaegi/releases/tag/v0.8.14) the support of [go1.13 has been dropped](https://github.com/containous/yaegi/pull/808)

I think that you are using go1.13, so I recommend to update your go version.

**Comment by mydockergit** [comment]
I upgraded to go1.15 and now it's ok, thanks
