### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by pjebs** [containous/yaegi#842]
This is an excellent package.
I would like to make a fork because obviously you wouldn't accept my package: https://github.com/rocketlaunchr/igo built in.

Can you point me to where in this package I need to modify to examine each input code line using ast package and make modifications to the ast?

Also can you tell me how I can preload a custom package so it's already included. I want to preload: `github.com/rocketlaunchr/dataframe-go` and `golang.org/x/exp/rand` (not math/rand or crypt/rand)

**Comment by mpl** [comment]
> This is an excellent package.
> I would like to make a fork because obviously you wouldn't accept my package: https://github.com/rocketlaunchr/igo built in.
> 
> Can you point me to where in this package I need to modify to examine each input code line using ast package and make modifications to the ast?

you can use the YAEGI_AST_DOT, and YAEGI_DOT_CMD environment variables to print the AST that was generated during a yaegi run.
The code using the Go parser to generate the AST is in interp/ast.go

> Also can you tell me how I can preload a custom package so it's already included. I want to preload: `github.com/rocketlaunchr/dataframe-go` and `golang.org/x/exp/rand` (not math/rand or crypt/rand)

I think you want to use the 'yaegi extract' command.
